# Generated by Django 3.0.3 on 2020-09-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('exchange', models.CharField(max_length=2)),
                ('production_data', models.DateTimeField()),
                ('interval', models.CharField(max_length=20)),
                ('volume', models.FloatField()),
                ('open_interest', models.FloatField()),
                ('open_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('close_price', models.FloatField()),
            ],
            options={
                'db_table': 'stock_data',
            },
        ),
    ]
