# Generated by Django 3.0.3 on 2020-09-07 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockdata',
            old_name='production_data',
            new_name='datetime',
        ),
    ]
