# Generated by Django 3.0.3 on 2020-09-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('procurement_data', models.DateTimeField()),
                ('production_data', models.DateTimeField()),
                ('code', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('producers', models.CharField(max_length=50)),
                ('speed', models.IntegerField()),
            ],
        ),
    ]
