# Generated by Django 3.0.3 on 2020-09-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_auto_20200904_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdata',
            name='procurement_data',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='production_data',
            field=models.DateField(null=True),
        ),
    ]
